title: Tinker CAD Studio
description: Dialectical • Behavior • Therapy  

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme


baseurl: "/dbt-workshop"
url: "https://lilashiba.github.io"

search_enabled: true

markdown: kramdown
highlighter: rouge

color_scheme: dark

aux_links:
  GitHub Repo: https://github.com/lilashiba/dbt-workshop