title: DBT Workshop
description: Dialectical • Behavior • Therapy

theme: just-the-docs

baseurl: "/dbt-workshop"
url: "https://lilashiba.github.io"

search_enabled: true

color_scheme: dark

aux_links:
  GitHub Repo: https://github.com/lilashiba/dbt-workshop